config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("diary.urls", namespace="diary")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path, include

from diary.views import (
    DiaryListView,
    DiaryCreateView,
    DiaryDetailsView,
    DiaryUpdateView,
    DiaryDeleteView,
    index,
)
from diary.apps import DearyConfig

app_name = DearyConfig.name

urlpatterns = [
    path("", index, name="index"),
    path("lists/", DiaryListView.as_view(), name="list"),
    path("create/", DiaryCreateView.as_view(), name="create"),
    path("detail/<int:pk>/", DiaryDetailsView.as_view(), name="detail"),
    path("update/<int:pk>/", DiaryUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", DiaryDeleteView.as_view(), name="delete"),
]

diary/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Diary(models.Model):
    title = models.CharField(max_length=200, verbose_name="Наименование")
    description = models.TextField(verbose_name="Текст", **NULLABLE)
    cd_date = models.DateField(verbose_name="Дата записи")
    image = models.ImageField(
        upload_to="diary/images/", verbose_name="Картинка", **NULLABLE
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Владелец")

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"

    def __str__(self):
        return f"{self.title} {self.description}"

diary/forms.py
from django import forms

from diary.models import Diary


class DiaryForm(forms.ModelForm):
    cd_date = forms.DateField(
        localize=True,
        widget=forms.DateInput(
            format="%Y-%m-%d", attrs={"class": "dr-form__input_date", "type": "date"}
        ),
    )

    class Meta:
        model = Diary
        exclude = ("owner",)
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "drpc-title input_diary", "placeholder": "Привет!"}
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "drpc text",
                    "placeholder": "Напиши что-нибудь интересное...",
                    "rows": 2,
                }
            ),
            "image": forms.FileInput(attrs={"class": "blockbtn__dfl-input"}),
        }

diary/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)

from diary.forms import DiaryForm
from diary.models import Diary
from diary.services import get_articles_from_cache
from users.permissions import IsOwner
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.permissions import IsAuthenticated


def index(request):
    context = {"title": '"Life Path" личный электронный дневник'}
    return render(request, "diary/index.html", context)


class DiaryListView(LoginRequiredMixin, ListView):
    model = Diary
    extra_context = {"title": "Архив записей"}

    def get_queryset(self):
        qs = get_articles_from_cache(user_id=self.request.user.id)

        if query := self.request.GET.get("q", ""):
            qs = qs.filter(Q(title__icontains=query) | Q(description__icontains=query))
        return qs

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["title"] = "Архив записей"
    #     context
    #     return context


class DiaryCreateView(CreateView):
    model = Diary
    form_class = DiaryForm
    permission_classes = [IsAuthenticated]

    def form_valid(self, form):
        diary = form.save(commit=False)
        user = self.request.user
        diary.owner = user
        diary.save()
        messages.success(self.request, "Запись успешно создана!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("diary:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Создание записи"
        return context


class DiaryDetailsView(DetailView):
    model = Diary
    permission_classes = [IsOwner]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Подробная информация записи"
        return context

    def get_queryset(self):
        return get_articles_from_cache()


class DiaryUpdateView(UpdateView):
    model = Diary
    form_class = DiaryForm

    def get_success_url(self):
        return reverse_lazy("diary:detail", args=[self.kwargs.get("pk")])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Редактирование записи"
        return context


class DiaryDeleteView(DeleteView):
    model = Diary
    success_url = reverse_lazy("diary:list")
    permission_classes = [IsOwner]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Удаление записи"
        return context

diary/templates/diary/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-bs-theme="light">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>{{ title }}</title>
    <link rel="icon" href="{% static 'images/logo.png' %}" sizes="16x16" type="image/png">
    <link rel="stylesheet" href="{% static 'css/static.css' %}">
    <link rel="stylesheet" href="{% static 'css/tiny-slider.css' %}">
    <link href="{% static 'css/app.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/bootstrap.min2.css' %}" rel="stylesheet">
    <link href="{% static 'css/album.css' %}" rel="stylesheet">

    <style>
        #alert-messages {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            z-index: 1050;
            padding: 15px 20px;
            background-color: rgba(144, 238, 144, 0.8);
            border-radius: 10px;
            font-size: 1.5em;
            display: none;
            max-width: 300px;
            text-align: center;
            box-shadow: 0 4px 8px rgba(0,0,0,0.2);
        }
        .fade-out {
            opacity: 0;
            transition: opacity 1s ease-out;
        }
    </style>

</head>
<body>
{% include 'diary/includes/inc_nav_menu.html' %}
{% block content %}
{% endblock %}

{% if request.path == '/diary/index/' %}
<footer class="text-muted">
    <div class="container">
        <p class="float-right"></p>
        <p>&copy; 2024 - {% now 'Y' %}</p>
    </div>
</footer>
{% endif %}

<!-- Место для отображения сообщений об успехе -->
{% if messages %}
    <div id="alert-messages" class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
    <script>
        document.getElementById("alert-messages").style.display = "block";
        setTimeout(function() {
            var alertMsg = document.getElementById("alert-messages");
            alertMsg.classList.add('fade-out');
            setTimeout(function() {
                alertMsg.style.display = "none";
            }, 1500); // Время на исчезновение (подходит под transition)
        }, 2500); // Показывать сообщение 2,5 секунды
    </script>
{% endif %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

diary/templates/diary/diary_confirm_delete.html
{% extends 'diary/base.html' %}
{% load my_tags %}
{% block content %}
<main class="main-box lock">
    <div class="page page-home">
        <div class="content-auto">
            <div class="container-fluid">
                <div class="form-center">
                    <div class="post-single">
                        <form method="post" class="row">
                            {% csrf_token %}
                            <div class="post-preview">
                                <div class="dr-post">
                                    <div class="dr-post__body" style="background-color: rgb(255, 255, 255);">
                                        <h1 class="dr-title__line dr-title__sm">
                                            Удаление записи
                                        </h1>
                                        <h1 style="text-align: center;">Вы уверены, что хотите удалить запись <br>"{{ object.title }}"?</h1>
                                        <button type="submit" class="btn btn-danger"
                                                style="font-size: 25px; margin-top: 40px;">Подтвердить
                                        </button>
                                        <br>
                                        <a href="{% url 'diary:list' %}" class="btn btn-success"
                                           style="font-size: 25px;">Отмена</a>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

diary/templates/diary/diary_detail.html
{% extends 'diary/base.html' %}
{% load my_tags %}
{% block content %}
<main class="main-box lock">
    <div class="content-auto" style="height: 100%">
        <div class="album py-5 page page-home"
             style="background-image: linear-gradient(145deg, rgba(131,206,237,1) 28.203505277633667%, rgba(122,191,255,1) 100%);">
            <div class="form-center" style="margin-top: -30px;">
                <div class="card col-6 dr-form__box">
                    <br>
                    <h2 class="dr-title__line dr-title__sm" style="margin-bottom: 10px;">{{ object.title }}</h2>
                    <div class="card-body">
                        <img class="img-center" src="{{ object.image | media_filter }}"
                             style="width: 32vw; height: auto; display: block; margin-left: auto; margin-right: auto; margin-bottom: 10px;"> <!-- Уменьшен отступ снизу -->
                        <br>
                        <p class="card-text">{{ object.description }}</p>
                        <br>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-success" href="{% url 'diary:list' %}" style="font-size: 20px;">Назад</a>
                                {% if object.owner == user %}
                                    <a class="btn btn-success" href="{% url 'diary:update' object.pk %}" style="font-size: 20px;">Изменить</a>
                                {% endif %}
                                {% if user.is_superuser or object.owner == user %}
                                    <a class="btn btn-success" href="{% url 'diary:delete' object.pk %}" style="color: red;">Удалить</a>
                                {% endif %}
                            </div>
                            <small class="text-muted">{{ object.cd_date }}</small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

diary/templates/diary/diary_form.html
{% extends 'diary/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<main class="main-box lock">
    <div class="content-auto">
        <div class="page page-home" style="background-color: rgb(136, 117, 183);">
            <div class="container-fluid">
                <div class="form-center">
                    <div class="post-single">
                        <form class="row" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="post-preview">
                                <div class="dr-post">
                                    <div class="dr-post__body" style="background-color: rgb(255, 255, 255);">
                                        <h1 class="dr-title__line dr-title__sm">{{title}}</h1>
                                        {{ form.title }}<br>
                                        {{ form.description }} <br>
                                        {% if object.image %}
                                        <div class="dr-form__group">
                                            <div class="dr-imgradio">
                                                <div class="dr-imgradio__item">
                                                    <div class="dr-imgradio__img">
                                                        <img src="{{ object.image | media_filter }}">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endif %}
                                        <label class="blockbtn__dfl">
                                            {{ form.image }}
                                            <svg width="34" height="34" viewBox="0 0 34 34"
                                                 fill="none"
                                                 xmlns="http://www.w3.org/2000/svg"
                                                 class="blockbtn__dfl-img">
                                                <path d="M17 25.5L6.375 14.875L9.35 11.7937L14.875 17.3187V0H19.125V17.3187L24.65 11.7937L27.625 14.875L17 25.5ZM4.25 34C3.08125 34 2.08108 33.5842 1.2495 32.7526C0.417916 31.921 0.00141667 30.9202 0 29.75V23.375H4.25V29.75H29.75V23.375H34V29.75C34 30.9187 33.5842 31.9196 32.7526 32.7526C31.921 33.5856 30.9202 34.0014 29.75 34H4.25Z"
                                                      fill="#FC9D74">
                                                </path>
                                            </svg>
                                            <div class="blockbtn__dfl-content">
                                                <div class="blockbtn__dfl-title">Загрузить с компьютера</div>
                                                <div class="blockbtn__dfl-text">JPEG, PNG, GIF, WEBP, размер до 6 Мб
                                                </div>
                                            </div>
                                        </label>
                                        {{ form.cd_date }}
                                        <br>
                                        <button type="submit" class="btn btn-success">
                                            {% if object %}
                                            Сохранить
                                            {% else %}
                                            Создать
                                            {% endif %}
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}
<script>document.getElementById('davaToday').valueAsDate = new Date();</script>
data-uk-datepicker="{weekstart:0, format:'DD.MM.YYYY'}"

diary/templates/diary/diary_list.html
{% extends 'diary/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<main class="main-box lock">
    <div class="content-auto">
        <div class="album py-5 page page-home" style="background-image: linear-gradient(145deg,rgba(131,206,237,1)28.203505277633667%,rgba(122,191,255,1)100%);">
            <h1 class="text_list text-center" style="color: #000;">{{ title }}</h1><br>
            <div class="container">
                <div class="row justify-content-center">
                    {% for object in object_list %}
                    <div class="col-md-3 mb-4">
                        <div class="card box-shadow h-100">
                            <img class="card-img-top" src="{{ object.image | media_filter }}" alt="{{ object.title }}" style="height: 150px; object-fit: cover;">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title text-center">
                                    {{ object.title }}
                                </h5>
                                <p class="card-text text-center" style="margin-top: auto;">{{ object.cd_date }}</p>
                                <div style="display: flex; justify-content: center;" class="mt-3">
                                    <div class="btn-group w-auto">
                                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'diary:detail' object.pk %}">Просмотр</a>
                                        {% if object.owner == user %}
                                            <a class="btn btn-sm btn-outline-secondary" href="{% url 'diary:update' object.pk %}">Редактировать</a>
                                        {% endif %}
                                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'diary:delete' object.pk %}">Удалить</a>
                                    </div>
                                </div>
                                {% if user.is_staff or user.is_superuser %}
                                    <p style="font-style: italic; color: gray; font-size: 0.8em;">
                                        {{ object.owner }}
                                    </p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}