config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("diary.urls", namespace="diary")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path, include

from diary.views import (
    DiaryListView,
    DiaryCreateView,
    DiaryDetailsView,
    DiaryUpdateView,
    DiaryDeleteView,
    index,
)
from diary.apps import DearyConfig

app_name = DearyConfig.name

urlpatterns = [
    path("", index, name="index"),
    path("lists/", DiaryListView.as_view(), name="list"),
    path("create/", DiaryCreateView.as_view(), name="create"),
    path("detail/<int:pk>/", DiaryDetailsView.as_view(), name="detail"),
    path("update/<int:pk>/", DiaryUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", DiaryDeleteView.as_view(), name="delete"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from django.urls import path

from users.views import (
    UserCreateView,
    email_verification,
    ProfileView,
    RegisterMessageView,
    PasswordRecoveryView,
    PasswordRecoveryMessageView,
)

app_name = UsersConfig.name


urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email_confirm/<str:token>/", email_verification, name="email_confirm"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("register/message/", RegisterMessageView.as_view(), name="register_message"),
    path(
        "password_recovery/", PasswordRecoveryView.as_view(), name="password_recovery"
    ),
    path(
        "password_recovery_message/",
        PasswordRecoveryMessageView.as_view(),
        name="recovery_message",
    ),
    path("profile/", ProfileView.as_view(), name="profile"),
]

diary/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Diary(models.Model):
    title = models.CharField(max_length=200, verbose_name="Наименование")
    description = models.TextField(verbose_name="Текст", **NULLABLE)
    cd_date = models.DateField(verbose_name="Дата записи")
    image = models.ImageField(
        upload_to="diary/images/", verbose_name="Картинка", **NULLABLE
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Владелец")

    class Meta:
        verbose_name = "Запись"
        verbose_name_plural = "Записи"

    def __str__(self):
        return f"{self.title} {self.description}"

diary/forms.py
from django import forms

from diary.models import Diary


class DiaryForm(forms.ModelForm):
    cd_date = forms.DateField(
        localize=True,
        widget=forms.DateInput(
            format="%Y-%m-%d", attrs={"class": "dr-form__input_date", "type": "date"}
        ),
    )

    class Meta:
        model = Diary
        exclude = ("owner",)
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "drpc-title input_diary", "placeholder": "Привет!"}
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "drpc text",
                    "placeholder": "Напиши что-нибудь интересное...",
                    "rows": 2,
                }
            ),
            "image": forms.FileInput(attrs={"class": "blockbtn__dfl-input"}),
        }

diary/views.py
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)

from diary.forms import DiaryForm
from diary.models import Diary
from diary.services import get_articles_from_cache
from users.permissions import IsOwner
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework.permissions import IsAuthenticated


def index(request):
    context = {"title": '"Life Path" личный электронный дневник'}
    return render(request, "diary/index.html", context)


class DiaryListView(LoginRequiredMixin, ListView):
    model = Diary
    extra_context = {"title": "Архив записей"}

    def get_queryset(self):
        qs = get_articles_from_cache(user_id=self.request.user.id)

        if query := self.request.GET.get("q", ""):
            qs = qs.filter(Q(title__icontains=query) | Q(description__icontains=query))
        return qs

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context["title"] = "Архив записей"
    #     context
    #     return context


class DiaryCreateView(CreateView):
    model = Diary
    form_class = DiaryForm
    permission_classes = [IsAuthenticated]

    def form_valid(self, form):
        diary = form.save(commit=False)
        user = self.request.user
        diary.owner = user
        diary.save()
        messages.success(self.request, "Запись успешно создана!")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("diary:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Создание записи"
        return context


class DiaryDetailsView(DetailView):
    model = Diary
    permission_classes = [IsOwner]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Подробная информация записи"
        return context

    def get_queryset(self):
        return get_articles_from_cache()


class DiaryUpdateView(UpdateView):
    model = Diary
    form_class = DiaryForm

    def get_success_url(self):
        return reverse_lazy("diary:detail", args=[self.kwargs.get("pk")])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Редактирование записи"
        return context


class DiaryDeleteView(DeleteView):
    model = Diary
    success_url = reverse_lazy("diary:list")
    permission_classes = [IsOwner]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Удаление записи"
        return context

diary/templates/diary/includes/inc_footer.html
<footer class="footer">
    <div class="container">
        <div class="footer__row">
            <div class="footer__left">
                <a href="https://Life-Path.ru/" class="footer__logo"><img
                        src="./Life-Path личный онлайн дневник_files/logo.svg" alt="Life-Path логотип"></a>
                <div class="footer__small">Сервис для ведения личных
                    онлайн-дневников и заметок
                </div>
            </div>
            <div class="footer__right">
                <h5 <br>
                    </h5>
                <a ></a>
            </div>
        </div>
    </div>
</footer>
<div class="container">
    <div class="copyright">
        <span class="copyright__text">&copy; 2024 - {% now 'Y' %}</span>
        <a target="_blank" href="https://Life-Path.ru/oferta" class="copyright__link"
           style="margin-right:15px">Оферта</a>
        <a target="_blank" href="https://Life-Path.ru/agreement" class="copyright__link">Cогласие на обработку
            персональных данных</a>
    </div>
</div>

diary/templates/diary/includes/inc_nav_menu.html
{% load my_tags %}
{% load static %}
<style>
    /* Стиль для фиксированной шапки */
    .header {
        background-color: #fff; /* Цвет фона */
        border-bottom: 1px solid #ddd; /* Граница снизу для визуального разделения */
        width: 100%; /* Полная ширина */
        position: fixed; /* Фиксированное положение */
        top: 0; /* Прикреплено к верхней части экрана */
        left: 0; /* Выровнено по левому краю */
        z-index: 1000; /* Чтобы быть поверх остальных элементов */
    }

    /* Отступ для основного содержимого, чтобы оно не перекрывалось шапкой */
    .content {
        margin-top: 80px; /* Увеличьте, если шапка выше */
    }
</style>

<header class="header">
    <div class="container-fluid">
        <div class="header-content">
            <div class="header-left" style="display: flex; align-items: center;">
                <img src="{% static 'images/logo.png' %}" width="50" height="50">
                <a href="{% url 'diary:index' %}" class="btn btn-purple ms-3">Главная</a>
            </div>
            {% if user.is_authenticated %}
            <div class="header-box">
                <div class="header-left__actions">
                    <a href="{% url 'diary:create' %}" class="btn btn-outline-secondary">Создать запись</a>
                    <a href="{% url 'diary:list' %}" class="btn btn-outline-secondary"
                       style="margin-left: 10px; margin-right: 10px;">Архив записей</a>
                </div>

                {% if request.path == '/lists/' %}
                <div class="dr-search">
                    <div class="dr-input__icon">
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none"
                             xmlns="http://www.w3.org/2000/svg" class="dr-input__icon-icon">
                            <path
                                d="M9.58329 17.5001C13.9555 17.5001 17.5 13.9557 17.5 9.58341C17.5 5.21116 13.9555 1.66675 9.58329 1.66675C5.21104 1.66675 1.66663 5.21116 1.66663 9.58341C1.66663 13.9557 5.21104 17.5001 9.58329 17.5001Z"
                                stroke="#FC9D74" stroke-width="1.5" stroke-linecap="round"
                                stroke-linejoin="round"></path>
                            <path d="M18.3333 18.3334L16.6666 16.6667" stroke="#FC9D74" stroke-width="1.5"
                                  stroke-linecap="round"
                                  stroke-linejoin="round"></path>
                        </svg>
                        <form method="GET" action="">
                            <input name="q" value="{{ query }}" autocomplete="off" placeholder="Поиск..."
                                   class="dr-input__flat">
                        </form>
                    </div>
                </div>
                {% endif %}
                <form id='UserForm' action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <li><a href="javascript:void(0);" onclick="document.getElementById('UserForm').submit();"
                           class="btn btn-outline-danger">Выйти</a></li>
                </form>

                <div class="dr-account" onclick="myFunction()">
                    <a href="{% url 'users:profile' %}" class="a-blok">
                        <div class="dr-account__header">
                            {% csrf_token %}
                            <div class="dr-account__name">
                                {{ user.username }}
                            </div>
                            <div class="dr-account-icon">
                                <div class="dr-account-icon__img">
                                    <img src="{{ user.avatar | media_filter }}">
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
            {% else %}
            {% if request.path == '/' %}
            <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#about">О нас</a>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#reasons">Зачем вести дневник? </a>
                <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="#start">Как начать?</a>
            </nav>
            {% endif %}
            {% endif %}
        </div>
    </div>
</header>