config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("", include("diary.urls", namespace="diary")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/urls.py
from django.urls import path, include

from diary.views import (
    DiaryListView,
    DiaryCreateView,
    DiaryDetailsView,
    DiaryUpdateView,
    DiaryDeleteView,
    index,
)
from diary.apps import DearyConfig

app_name = DearyConfig.name

urlpatterns = [
    path("", index, name="index"),
    path("lists/", DiaryListView.as_view(), name="list"),
    path("create/", DiaryCreateView.as_view(), name="create"),
    path("detail/<int:pk>/", DiaryDetailsView.as_view(), name="detail"),
    path("update/<int:pk>/", DiaryUpdateView.as_view(), name="update"),
    path("delete/<int:pk>/", DiaryDeleteView.as_view(), name="delete"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from django.urls import path

from users.views import (
    UserCreateView,
    email_verification,
    ProfileView,
    RegisterMessageView,
    PasswordRecoveryView,
    PasswordRecoveryMessageView,
)

app_name = UsersConfig.name


urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email_confirm/<str:token>/", email_verification, name="email_confirm"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("register/message/", RegisterMessageView.as_view(), name="register_message"),
    path(
        "password_recovery/", PasswordRecoveryView.as_view(), name="password_recovery"
    ),
    path(
        "password_recovery_message/",
        PasswordRecoveryMessageView.as_view(),
        name="recovery_message",
    ),
    path("profile/", ProfileView.as_view(), name="profile"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {"blank": True, "null": True}


class User(AbstractUser):
    username = models.CharField(max_length=100, verbose_name="Никнейм")
    email = models.EmailField(unique=True, verbose_name="Почта")
    last_name = models.CharField(max_length=150, verbose_name="Фамилия", **NULLABLE)
    first_name = models.CharField(max_length=100, verbose_name="Имя", **NULLABLE)
    avatar = models.ImageField(
        upload_to="users/avatar/", verbose_name="Аватар", **NULLABLE
    )
    token = models.CharField(max_length=100, verbose_name="Токен", **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

    def __str__(self):
        return f"{self.username} {self.last_name} {self.first_name} {self.email} "

users/forms.py
from django.contrib.auth.forms import (
    UserCreationForm,
    UserChangeForm,
    AuthenticationForm,
)
from django import forms

from users.models import User


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1")


class UserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "last_name",
            "first_name",
            "avatar",
        )
        widgets = {
            "username": forms.TextInput(attrs={"class": "dr-form__input"}),
            "last_name": forms.TextInput(attrs={"class": "dr-form__input"}),
            "first_name": forms.TextInput(attrs={"class": "dr-form__input"}),
            "email": forms.EmailInput(attrs={"class": "dr-form__input"}),
            "avatar": forms.FileInput(attrs={"class": "blockbtn__dfl-input"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["password"].widget = forms.HiddenInput()


class PasswordRecoveryForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email",)

users/views.py
import secrets

from django.contrib import messages
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, TemplateView, DetailView

from config.settings import EMAIL_HOST_USER
from users.forms import UserRegisterForm, UserProfileForm, PasswordRecoveryForm
from users.models import User
from users.utils import send_email_confirm


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = "users/register.html"
    success_url = reverse_lazy("users:register_message")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}/"
        send_email_confirm(url, user.email)

        messages.success(
            self.request,
            "Ссылка для подтверждения вашего email была отправлена на указанный адрес.",
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Профиль"
        return context


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()

    messages.success(
        request, "Ваш email был успешно подтвержден! Теперь вы можете войти в систему."
    )
    return redirect(reverse("users:login"))


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Профиль"
        return context


class RegisterMessageView(TemplateView):
    template_name = "users/register_message.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Профиль"
        return context


class PasswordRecoveryMessageView(TemplateView):
    template_name = "users/password_recovery_message.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Профиль"
        return context


class PasswordRecoveryView(TemplateView):
    model = User
    template_name = "users/password_recovery_form.html"
    form_class = PasswordRecoveryForm
    success_url = reverse_lazy("users:recovery_message")

    def post(self, request, *args, **kwargs):
        email = request.POST.get("email")
        user = User.objects.get(email=email)
        token = secrets.token_hex(10)
        user.set_password(token)
        user.save()

        host = self.request.get_host()
        url = f"http://{host}/users/login/"

        send_mail(
            "Восстановление пароля",
            f"Ваш новый пароль {token}, перейдите по ссылке {url}",
            EMAIL_HOST_USER,
            [user.email],
        )
        return HttpResponseRedirect("/users/password_recovery_message/")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Восстановление пароля"
        return context

users/templates/users/login.html
{% extends 'diary/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<main class="main-box lock">
    <div class="content">
        <section class="screen_reg">
            <div class="form-center">
                {% if user.is_authenticated %}
                <div class="dr-reg__form">
                    <h1 class="dr-title__line">Привет, {{ user.username }}</h1>
                    <div class="dr-form__group">
                        <div class="logged__avatar">
                            <img width="10" height="10" src="{{ user.avatar | media_filter }}">
                        </div>
                    </div>
                    <div class="dr-form__group-action">
                        <a href="{% url 'diary:list' %}" class="btn btn-success btn-lg btn-block">
                            Мои записи
                        </a>
                        <div class="auth-form__forgot">
                            <form action="{% url 'users:logout' %}" method="post">
                                {% csrf_token %}
                                <button class="btn btn-success btn-lg btn-block" type="submit">
                                    Выход
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            {% else %}
            <div class="dr-reg__form">
                <form method="POST">
                    {% csrf_token %}
                    <div class="dr-form__group">
                        <label for="email" class="dr-form__label">Email</label>
                        <div class="dr-form__group-icon">
                            <svg class="dr-form__icon" width="25" height="24" viewBox="0 0 25 24"
                                 fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M11.9805 8.99951C10.364 8.99951 9.05351 10.3427 9.05351 11.9995C9.05351 13.6564 10.364 14.9995 11.9805 14.9995C13.5971 14.9995 14.9075 13.6564 14.9075 11.9995C14.9075 10.3427 13.5971 8.99951 11.9805 8.99951ZM7.10217 11.9995C7.10217 9.23809 9.28628 6.99951 11.9805 6.99951C14.6748 6.99951 16.8589 9.23809 16.8589 11.9995C16.8589 14.7609 14.6748 16.9995 11.9805 16.9995C9.28628 16.9995 7.10217 14.7609 7.10217 11.9995Z"
                                      fill="#FC9D74"></path>
                                <path fill-rule="evenodd" clip-rule="evenodd"
                                      d="M7.39497 2.05462C9.585 0.993863 12.0607 0.723624 14.4196 1.28784C16.7785 1.85206 18.8818 3.21756 20.3875 5.1623C21.8932 7.10704 22.7127 9.51665 22.7129 11.9993V12.9994C22.7129 14.0602 22.3017 15.0777 21.5698 15.8278C20.8379 16.5779 19.8453 16.9994 18.8102 16.9994C17.7752 16.9994 16.7825 16.5779 16.0506 15.8278C15.3187 15.0777 14.9075 14.0602 14.9075 12.9994V7.99938C14.9075 7.44709 15.3444 6.99938 15.8832 6.99938C16.4221 6.99938 16.8589 7.44709 16.8589 7.99938V12.9994C16.8589 13.5298 17.0645 14.0385 17.4304 14.4136C17.7964 14.7887 18.2927 14.9994 18.8102 14.9994C19.3277 14.9994 19.8241 14.7887 20.19 14.4136C20.556 14.0385 20.7616 13.5298 20.7616 12.9994V11.9994C20.7616 11.9994 20.7616 11.9995 20.7616 11.9994C20.7614 9.96819 20.0909 7.99665 18.8589 6.40552C17.627 4.81437 15.9061 3.69714 13.9761 3.23551C12.0462 2.77388 10.0206 2.99498 8.22871 3.86287C6.43687 4.73076 4.98417 6.1944 4.10682 8.01579C3.22948 9.83718 2.97908 11.9092 3.39636 13.8949C3.81363 15.8807 4.87404 17.6633 6.40514 18.9531C7.93625 20.2428 9.848 20.9637 11.8296 20.9987C13.8111 21.0336 15.7459 20.3804 17.3194 19.1454C17.7472 18.8096 18.3596 18.8929 18.6872 19.3314C19.0148 19.7698 18.9336 20.3975 18.5058 20.7333C16.5827 22.2428 14.2179 23.0411 11.796 22.9984C9.37411 22.9557 7.03751 22.0745 5.16616 20.4982C3.29481 18.9219 1.99877 16.743 1.48876 14.316C0.978761 11.889 1.2848 9.35655 2.35711 7.13041C3.42942 4.90427 5.20494 3.11538 7.39497 2.05462Z"
                                      fill="#FC9D74"></path>
                            </svg>
                            <input type="text" name="username" id="username"
                                   class="dr-form__input">
                        </div>
                    </div>
                    <div class="dr-form__group">
                        <label for="header-password" class="dr-form__label">Пароль</label>
                        <div class="dr-form__group-icon">
                            <svg class="dr-form__icon" width="24" height="24" viewBox="0 0 24 24"
                                 fill="none" xmlns="http://www.w3.org/2000/svg">
                                <path
                                        d="M6.18014 22.75C6.08014 22.75 5.97014 22.74 5.88014 22.73L3.71014 22.43C2.67014 22.29 1.73014 21.36 1.57014 20.3L1.27014 18.11C1.17014 17.41 1.47014 16.5 1.97014 15.99L6.36014 11.6C5.65014 8.75999 6.47014 5.75998 8.56014 3.68998C11.8001 0.459984 17.0701 0.449984 20.3201 3.68998C21.8901 5.25998 22.7501 7.34998 22.7501 9.56998C22.7501 11.79 21.8901 13.88 20.3201 15.45C18.2201 17.53 15.2301 18.35 12.4101 17.63L8.01014 22.02C7.59014 22.46 6.84014 22.75 6.18014 22.75ZM14.4301 2.75998C12.6801 2.75998 10.9401 3.41998 9.61014 4.74998C7.81014 6.53998 7.16014 9.15999 7.91014 11.6C7.99014 11.87 7.92014 12.15 7.72014 12.35L3.02014 17.05C2.85014 17.22 2.71014 17.66 2.74014 17.89L3.04014 20.08C3.10014 20.46 3.51014 20.89 3.89014 20.94L6.07014 21.24C6.31014 21.28 6.75014 21.14 6.92014 20.97L11.6401 16.26C11.8401 16.06 12.1301 16 12.3901 16.08C14.8001 16.84 17.4301 16.19 19.2301 14.39C20.5101 13.11 21.2201 11.39 21.2201 9.56998C21.2201 7.73998 20.5101 6.02998 19.2301 4.74998C17.9301 3.42998 16.1801 2.75998 14.4301 2.75998Z"
                                        fill="#FC9D74"></path>
                                <path
                                        d="M9.19008 20.54C9.00008 20.54 8.81008 20.47 8.66008 20.32L6.36008 18.02C6.07008 17.73 6.07008 17.25 6.36008 16.96C6.65008 16.67 7.13008 16.67 7.42008 16.96L9.72008 19.26C10.0101 19.55 10.0101 20.03 9.72008 20.32C9.57008 20.47 9.38008 20.54 9.19008 20.54Z"
                                        fill="#FC9D74"></path>
                                <path
                                        d="M14.5 11.75C13.26 11.75 12.25 10.74 12.25 9.5C12.25 8.26 13.26 7.25 14.5 7.25C15.74 7.25 16.75 8.26 16.75 9.5C16.75 10.74 15.74 11.75 14.5 11.75ZM14.5 8.75C14.09 8.75 13.75 9.09 13.75 9.5C13.75 9.91 14.09 10.25 14.5 10.25C14.91 10.25 15.25 9.91 15.25 9.5C15.25 9.09 14.91 8.75 14.5 8.75Z"
                                        fill="#FC9D74"></path>
                            </svg>
                            <input type="password" name="password" id="pwd"
                                   class="dr-form__input" required autocomplete="current-password">
                        </div>
                    </div>
                    <div class="dr-form__group-action">
                        <button type="submit" class="btn btn-success btn-lg btn-block">Войти
                        </button>
                        <div class="auth-form__forgot">
                            <a href="{% url 'users:password_recovery' %}" class="btn btn-success btn-lg btn-block">Забыли
                                пароль?</a>
                        </div>
                    </div>
                </form>
            </div>
            {% endif %}
    </div>
    <br>
    </section>
    </div>
</main>
{% endblock %}

users/templates/users/profile.html
{% extends 'diary/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<main class="main-box lock"><!---->
    <div class="content">
        <div class="form-page form-profile">
            <div class="form-page__box">
                <div class="dr-form__box">
                    <h2 class="dr-title__line dr-title__sm">
                        Профиль
                    </h2>
                    <p class="text-center"><img class="text-center" src="{{ user.avatar | media_filter }}"
                                                width="100" height="100">
                    </p>
                    <p class="dr-form__p">Никнейм: {{ user.username }}</p>
                    <p class="dr-form__p">Фамилия: {{ user.last_name }}</p>
                    <p class="dr-form__p">Имя: {{ user.first_name }}</p>
                    <p class="dr-form__p">E-mail: {{ user.email }}</p>
                    <a href="{% url 'users:profile' %}" class="dr-btn__border no_link">Редактировать профиль</a>

                </div>
                <div class="form-page__action">
                    <a href="{% url 'diary:list' %}" class="dr-btn dr-btn__coral dr-btn__small">Вернуться назад</a>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/user_form.html
{% extends 'diary/base.html' %}
{% load static %}
{% load my_tags %}
{% block content %}
<main class="main-box lock"><!---->
    <div class="content">
        <div class="form-page form-profile">
            <div class="form-page__box">
                <div class="dr-form__box">
                    <h2 class="dr-title__line dr-title__sm">
                        Профиль
                    </h2>
                    <form class="dr-form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="dr-form__group">
                            <div class="dr-form__group-icon">
                                <p class="text-center">
                                    <img src="{{ user.avatar | media_filter }}" width="80" height="80">
                                </p>
                            </div>
                        </div>
                        <div class="dr-form__group">
                            <label for="id_username" class="dr-form__label">Никнейм</label>
                            <div class="dr-form__group-icon">
                                <svg class="dr-form__icon" width="24" height="24" viewBox="0 0 24 24" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path d="M18.1399 21.62C17.2599 21.88 16.2199 22 14.9999 22H8.99986C7.77986 22 6.73986 21.88 5.85986 21.62C6.07986 19.02 8.74986 16.97 11.9999 16.97C15.2499 16.97 17.9199 19.02 18.1399 21.62Z"
                                          stroke="#FC9D74" stroke-width="1.5" stroke-linecap="round"
                                          stroke-linejoin="round">
                                    </path>
                                    <path d="M15 2H9C4 2 2 4 2 9V15C2 18.78 3.14 20.85 5.86 21.62C6.08 19.02 8.75 16.97 12 16.97C15.25 16.97 17.92 19.02 18.14 21.62C20.86 20.85 22 18.78 22 15V9C22 4 20 2 15 2ZM12 14.17C10.02 14.17 8.42 12.56 8.42 10.58C8.42 8.60002 10.02 7 12 7C13.98 7 15.58 8.60002 15.58 10.58C15.58 12.56 13.98 14.17 12 14.17Z"
                                          stroke="#FC9D74" stroke-width="1.5" stroke-linecap="round"
                                          stroke-linejoin="round">
                                    </path>
                                    <path d="M15.5799 10.58C15.5799 12.56 13.9799 14.17 11.9999 14.17C10.0199 14.17 8.41992 12.56 8.41992 10.58C8.41992 8.60002 10.0199 7 11.9999 7C13.9799 7 15.5799 8.60002 15.5799 10.58Z"
                                          stroke="#FC9D74" stroke-width="1.5" stroke-linecap="round"
                                          stroke-linejoin="round">
                                    </path>
                                </svg>
                                {{ form.username }}
                            </div>
                        </div>
                        <div class="dr-form__group">
                            <label for="id_last_name" class="dr-form__label">Фамилия</label>
                            <div class="dr-form__group-icon">
                                <svg class="dr-form__icon" width="24" height="24" viewBox="0 0 24 24" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path d="M18.1399 21.62C17.2599 21.88 16.2199 22 14.9999 22H8.99986C7.77986 22 6.73986 21.88 5.85986 21.62C6.07986 19.02 8.74986 16.97 11.9999 16.97C15.2499 16.97 17.9199 19.02 18.1399 21.62Z"
                                          stroke="#FC9D74" stroke-width="1.5" stroke-linecap="round"
                                          stroke-linejoin="round">
                                    </path>
                                    <path d="M15 2H9C4 2 2 4 2 9V15C2 18.78 3.14 20.85 5.86 21.62C6.08 19.02 8.75 16.97 12 16.97C15.25 16.97 17.92 19.02 18.14 21.62C20.86 20.85 22 18.78 22 15V9C22 4 20 2 15 2ZM12 14.17C10.02 14.17 8.42 12.56 8.42 10.58C8.42 8.60002 10.02 7 12 7C13.98 7 15.58 8.60002 15.58 10.58C15.58 12.56 13.98 14.17 12 14.17Z"
                                          stroke="#FC9D74" stroke-width="1.5" stroke-linecap="round"
                                          stroke-linejoin="round">
                                    </path>
                                    <path d="M15.5799 10.58C15.5799 12.56 13.9799 14.17 11.9999 14.17C10.0199 14.17 8.41992 12.56 8.41992 10.58C8.41992 8.60002 10.0199 7 11.9999 7C13.9799 7 15.5799 8.60002 15.5799 10.58Z"
                                          stroke="#FC9D74" stroke-width="1.5" stroke-linecap="round"
                                          stroke-linejoin="round">
                                    </path>
                                </svg>
                                {{ form.last_name }}
                            </div>
                        </div>
                        <div class="dr-form__group">
                            <label for="id_first_name" class="dr-form__label">Имя</label>
                            <div class="dr-form__group-icon">
                                <svg class="dr-form__icon" width="24" height="24" viewBox="0 0 24 24" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path d="M18.1399 21.62C17.2599 21.88 16.2199 22 14.9999 22H8.99986C7.77986 22 6.73986 21.88 5.85986 21.62C6.07986 19.02 8.74986 16.97 11.9999 16.97C15.2499 16.97 17.9199 19.02 18.1399 21.62Z"
                                          stroke="#FC9D74" stroke-width="1.5" stroke-linecap="round"
                                          stroke-linejoin="round">
                                    </path>
                                    <path d="M15 2H9C4 2 2 4 2 9V15C2 18.78 3.14 20.85 5.86 21.62C6.08 19.02 8.75 16.97 12 16.97C15.25 16.97 17.92 19.02 18.14 21.62C20.86 20.85 22 18.78 22 15V9C22 4 20 2 15 2ZM12 14.17C10.02 14.17 8.42 12.56 8.42 10.58C8.42 8.60002 10.02 7 12 7C13.98 7 15.58 8.60002 15.58 10.58C15.58 12.56 13.98 14.17 12 14.17Z"
                                          stroke="#FC9D74" stroke-width="1.5" stroke-linecap="round"
                                          stroke-linejoin="round">
                                    </path>
                                    <path d="M15.5799 10.58C15.5799 12.56 13.9799 14.17 11.9999 14.17C10.0199 14.17 8.41992 12.56 8.41992 10.58C8.41992 8.60002 10.0199 7 11.9999 7C13.9799 7 15.5799 8.60002 15.5799 10.58Z"
                                          stroke="#FC9D74" stroke-width="1.5" stroke-linecap="round"
                                          stroke-linejoin="round">
                                    </path>
                                </svg>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="dr-form__group">
                            <label for="id_email" class="dr-form__label">Email</label>
                            <div class="dr-form__group-icon">
                                <svg class="dr-form__icon" width="24" height="24" viewBox="0 0 24 24" fill="none"
                                     xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule='evenodd' clip-rule="evenodd"
                                          d="M11.9805 8.99951C10.364 8.99951 9.05351 10.3427 9.05351 11.9995C9.05351 13.6564 10.364 14.9995 11.9805 14.9995C13.5971 14.9995 14.9075 13.6564 14.9075 11.9995C14.9075 10.3427 13.5971 8.99951 11.9805 8.99951ZM7.10217 11.9995C7.10217 9.23809 9.28628 6.99951 11.9805 6.99951C14.6748 6.99951 16.8589 9.23809 16.8589 11.9995C16.8589 14.7609 14.6748 16.9995 11.9805 16.9995C9.28628 16.9995 7.10217 14.7609 7.10217 11.9995Z"
                                          fill="#FC9D74">
                                    </path>
                                    <path fill-rule='evenodd' clip-rule="evenodd"
                                          d="M7.39497 2.05462C9.585 0.993863 12.0607 0.723624 14.4196 1.28784C16.7785 1.85206 18.8818 3.21756 20.3875 5.1623C21.8932 7.10704 22.7127 9.51665 22.7129 11.9993V12.9994C22.7129 14.0602 22.3017 15.0777 21.5698 15.8278C20.8379 16.5779 19.8453 16.9994 18.8102 16.9994C17.7752 16.9994 16.7825 16.5779 16.0506 15.8278C15.3187 15.0777 14.9075 14.0602 14.9075 12.9994V7.99938C14.9075 7.44709 15.3444 6.99938 15.8832 6.99938C16.4221 6.99938 16.8589 7.44709 16.8589 7.99938V12.9994C16.8589 13.5298 17.0645 14.0385 17.4304 14.4136C17.7964 14.7887 18.2927 14.9994 18.8102 14.9994C19.3277 14.9994 19.8241 14.7887 20.19 14.4136C20.556 14.0385 20.7616 13.5298 20.7616 12.9994V11.9994C20.7616 11.9994 20.7616 11.9995 20.7616 11.9994C20.7614 9.96819 20.0909 7.99665 18.8589 6.40552C17.627 4.81437 15.9061 3.69714 13.9761 3.23551C12.0462 2.77388 10.0206 2.99498 8.22871 3.86287C6.43687 4.73076 4.98417 6.1944 4.10682 8.01579C3.22948 9.83718 2.97908 11.9092 3.39636 13.8949C3.81363 15.8807 4.87404 17.6633 6.40514 18.9531C7.93625 20.2428 9.848 20.9637 11.8296 20.9987C13.8111 21.0336 15.7459 20.3804 17.3194 19.1454C17.7472 18.8096 18.3596 18.8929 18.6872 19.3314C19.0148 19.7698 18.9336 20.3975 18.5058 20.7333C16.5827 22.2428 14.2179 23.0411 11.796 22.9984C9.37411 22.9557 7.03751 22.0745 5.16616 20.4982C3.29481 18.9219 1.99877 16.743 1.48876 14.316C0.978761 11.889 1.2848 9.35655 2.35711 7.13041C3.42942 4.90427 5.20494 3.11538 7.39497 2.05462Z"
                                          fill="#FC9D74">
                                    </path>
                                </svg>
                                {{ form.email }}
                            </div>
                        </div>
                        <label class="blockbtn__dfl">
                            {{ form.avatar }}
                            <svg width="34" height="34" viewBox="0 0 34 34"
                                 fill="none"
                                 xmlns="http://www.w3.org/2000/svg"
                                 class="blockbtn__dfl-img">
                                <path d="M17 25.5L6.375 14.875L9.35 11.7937L14.875 17.3187V0H19.125V17.3187L24.65 11.7937L27.625 14.875L17 25.5ZM4.25 34C3.08125 34 2.08108 33.5842 1.2495 32.7526C0.417916 31.921 0.00141667 30.9202 0 29.75V23.375H4.25V29.75H29.75V23.375H34V29.75C34 30.9187 33.5842 31.9196 32.7526 32.7526C31.921 33.5856 30.9202 34.0014 29.75 34H4.25Z"
                                      fill="#FC9D74">
                                </path>
                            </svg>
                            <div class="blockbtn__dfl-content">
                                <div class="blockbtn__dfl-title" style="margin-top: 5px;">Загрузить аватар</div>
                            </div>
                        </label>
                        <button type="submit" class="btn btn-success btn-lg btn-block" style="margin-top: 20px;">Редактировать профиль</button>
                    </form>
                </div>
                <div class="form-page__action">
                    <a href="{% url 'diary:list' %}" class="dr-btn dr-btn__coral dr-btn__small">Вернуться
                        назад</a>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock %}